# Generated by Django 5.1.7 on 2025-03-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0007_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='avatars/'),
        ),
    ]
