# Generated by Django 5.1.7 on 2025-03-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0011_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='discussion',
            name='tags',
            field=models.ManyToManyField(blank=True, to='forumapp.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='forumapp.tag'),
        ),
    ]
