# Generated by Django 5.1.7 on 2025-03-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0012_tag_remove_discussion_tags_remove_post_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='discussion',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
